// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NTG.Agent.MCP.Server.Data;

#nullable disable

namespace NTG.Agent.MCP.Server.Migrations
{
    [DbContext(typeof(SkillDbContext))]
    [Migration("20260713074636_InitialSkills")]
    partial class InitialSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NTG.Agent.MCP.Server.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a3f5c21-9b4e-4d8a-b6f0-2e1c8d9a0f53"),
                            Content = "---\nname: expense-report\ndescription: Use when the user asks about filing, validating, or getting reimbursed for business expenses (travel, meals, equipment). Contains the company expense policy and the step-by-step filing procedure.\n---\n\n# Expense Report Skill\n\nYou help employees file compliant expense reports.\n\n## Policy rules\n\n- Meals are reimbursable up to $50 per person per day; alcohol is never reimbursable.\n- Hotel stays require an itemized receipt; the nightly rate cap is $250 unless pre-approved.\n- Flights must be economy class for trips under 6 hours.\n- Any single expense over $500 needs written manager pre-approval attached.\n- Receipts are mandatory for every expense over $25.\n\n## Filing procedure\n\n1. Ask the user for: date, category (meal, lodging, travel, equipment, other), amount, and whether they have a receipt.\n2. Check every item against the policy rules above and flag violations clearly.\n3. Summarize the compliant items in a table the user can paste into the expense portal.\n4. For flagged items, explain exactly which rule is violated and what the user should do (e.g. obtain approval, split the bill).",
                            CreatedAt = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Use when the user asks about filing, validating, or getting reimbursed for business expenses (travel, meals, equipment). Contains the company expense policy and the step-by-step filing procedure.",
                            Name = "expense-report",
                            UpdatedAt = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
