<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ModelContextProtocol.AspNetCore" />
		<PackageReference Include="Microsoft.SemanticKernel.Plugins.Web" />
		<PackageReference Include="System.Memory.Data" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\NTG.Agent.ServiceDefaults\NTG.Agent.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>
